### ISSUE TITLE
Review & update existing user research process guidelines

### ISSUE THREAD

**Issue by lfriedman1321** [criminaljusticehub/sprint-board#31]
## What 
Gavin to review any existing guidelines for user research & communicate to team
Understand if there's a process that's been in place beforehand, and communicate what that process looks like for the research & design teams.

## Acceptance Criteria

- [x] Confirmation of any existing guidelines for user research
- [x] If no existing guidelines, updates ones are created which include high-level process and types of research
- [x] Create a User Research manifesto
- [x] Outline the research approach
- [ ] Guidelines have been shared with wider team

## Readiness

***Please check this meets the Definition of Ready before it is added to the backlog***
- [ ] The story or task has a **concise and understandable description**
- [ ] **Acceptance criteria** are specific, well-defined to clarify when task is considered complete
- [ ] Any **dependencies**, whether they are on other tasks/teams/external factors, are clearly outlined
- [ ] Initial **estimation** of effort or complexity is provided to help with prioritisation and planning
- [ ] The task has been assigned a **priority** level indicating importance in overall backlog
- [ ] Any relevant **attachments** - documents, mock-ups, additional info - that aid understanding are attached
- [ ] Clear how task will be **tested** to ensure it meets specified criteria
- [ ] All relevant **stakeholders** have provided input or approval for task

***Please check this meets the Definition of Done. before it is moved to the 'done' column***

- [ ] All code related to task is implemented and reviewed
- [ ] Unit tests written and passed to ensure functionality works as intended
- [ ] Integration Tests conducted to verify implemented code works well with other components
- [ ] Necessary documentation is complete, including code comments and user documentation
- [ ] Code has undergone a thorough review by peers or designated reviewer
- [ ] Task meets all acceptance criteria
- [ ] Comprehensive testing including regression testing has been performed to fix any bugs
- [ ] Performance aspects e.g., speed & resource usage, considered and meet defined standards
- [ ] Code ready for deployment in live environment
- [ ] Product manager or relevant stakeholders reviewed and approved completed task

**Comment by lfriedman1321** [comment]
Gavin has received some links from Ryan to review, from gov.uk

**Comment by noniUR** [comment]
### Tasks to complete to meet Definition of Done
- [ ] Review existing material on user research processes
- [ ] Identify topics to include
- [ ] Create guideline template
- [ ] Create draft user research guideline 
- [ ] Share draft guideline with team for feedback
- [ ] Make updates to draft guideline based on team feedback
- [ ] Upload to SharePoint

**Comment by noniUR** [comment]
Draft manifesto document and approach document created and available here: [User Research Strategy]([User Research Strategy](https://criminaljusticesystem.sharepoint.com/:f:/s/criminal-justice-hub-service-design-team/EhXdH3OlcitFmW3aDhdBdyQBc3_hvgHvXLAmA8D13LLz3Q?e=il6SZ9))

**Comment by noniUR** [comment]
User Research Master Sheet, Research Objectives Template (Miro), Information Sheet Template and Folder Structure created in SharePoint

**Comment by lfriedman1321** [comment]
@legaleagleryan can you please review in Gavin's absence?

**Comment by noniUR** [comment]
Adjusted the manifesto to cover both User research in Discovery and in Alpha and updated dates based on the Product Roadmap

**Comment by lfriedman1321** [comment]
@legaleagleryan n to check and sign off - let the team know when drafts are approved

**Comment by legaleagleryan** [comment]
Hey @rickypal1 please can you review this on your return. Wanted to make sure your ok with this going forward as Head of UR 🙂
