### ISSUE TITLE
Agree checklist for content audits

### ISSUE THREAD

**Issue by lfriedman1321** [criminaljusticehub/sprint-board#52]
## What
We need to agree what needs to be checked in the content audits so volunteers have a checklist to go through when reviewing all existing content. This should include content, accessibility, and technical aspects so will require input from all team members.

## Acceptance Criteria
*Describe the acceptance criteria for this specific issue to meet to be considered finished*

- [ ] Engineers have reviewed checklist
- [ ] Checklist is clear and covers everything that needs to be checked when reviewing existing content
- [ ] Checklist is available/accessible to all volunteers

## Readiness

***Please check this meets the Definition of Ready before it is added to the backlog***
- [ ] The story or task has a **concise and understandable description**
- [ ] **Acceptance criteria** are specific, well-defined to clarify when task is considered complete
- [ ] Any **dependencies**, whether they are on other tasks/teams/external factors, are clearly outlined
- [ ] Initial **estimation** of effort or complexity is provided to help with prioritisation and planning
- [ ] The task has been assigned a **priority** level indicating importance in overall backlog
- [ ] Any relevant **attachments** - documents, mock-ups, additional info - that aid understanding are attached
- [ ] Clear how task will be **tested** to ensure it meets specified criteria
- [ ] All relevant **stakeholders** have provided input or approval for task

***Please check this meets the Definition of Done. before it is moved to the 'done' column***

- [ ] All code related to task is implemented and reviewed
- [ ] Unit tests written and passed to ensure functionality works as intended
- [ ] Integration Tests conducted to verify implemented code works well with other components
- [ ] Necessary documentation is complete, including code comments and user documentation
- [ ] Code has undergone a thorough review by peers or designated reviewer
- [ ] Task meets all acceptance criteria
- [ ] Comprehensive testing including regression testing has been performed to fix any bugs
- [ ] Performance aspects e.g., speed & resource usage, considered and meet defined standards
- [ ] Code ready for deployment in live environment
- [ ] Product manager or relevant stakeholders reviewed and approved completed task

**Comment by lfriedman1321** [comment]
@criminaljusticehub/devops-team could you please pull together a list of things from a dev perspective that should be checked on each existing page before migrating it to the new site?

**Comment by lfriedman1321** [comment]
back end can check broken links and blocks, and missing media

**Comment by lfriedman1321** [comment]
Have started a checklist here can @criminaljusticehub/devops-team and @criminaljusticehub/content-design-team please review and add anything else? I've started adding some bits that would need to happen after.
@criminaljusticehub/devops-team team are you planning to backup all existing content?
https://criminaljusticesystem-my.sharepoint.com/:w:/g/personal/leah_friedman_criminaljusticehub_org_uk/EUrpQ65gWNVDjSGiP-O2UogBX5c5KLWI9_Zmp5zndvINpg?e=yBQAeu

**Comment by lfriedman1321** [comment]
After the content run-through/practice, list of questions for @legaleagleryan to work through to understand our approach to auditing content

**Comment by lfriedman1321** [comment]
Content Master Plan checklist agreed
