### ISSUE TITLE
Create initial user research roadmap/plan

### ISSUE THREAD

**Issue by lfriedman1321** [criminaljusticehub/sprint-board#92]
This is a task that @criminaljusticehub/user-research-team is undertaking together - we need to get an initial research plan in place, with a sequential, planned approach of what user research activities the team is undertaking and what the outcomes will be. 
For example - we have already completed Google Analytics research, which has helped us understand what content is working or not relevant. We may want to use the survey on the old website to start defining target audiences, and interviews to build user personas. We may then want further interviews, desk research, competitor research, etc. to start defining new content.

- [ ] Linked to #129 

Acceptance criteria:

- [ ] Research plan has been created with clear sequential steps and planned timelines
- [ ] Each research activity is mapped to an outcome/goal of the project
- [ ] A way to check on progress and update the plan is agreed

**Comment by lfriedman1321** [comment]
Initial high level roadmap held on product wall: https://miro.com/app/board/uXjVNKpVzaY=/

**Comment by lfriedman1321** [comment]
@criminaljusticehub/user-research-team have started adding red stickies to the high level roadmap to map to outcomes we want to achieve from conducting research, to inform our planning
